build:
  base-ref: debian:bookworm-slim@sha256:98f4b71de414932439ac6ac690d7060df1f27161073c5036a7553723881bffbe
  destination-path: /usr/local/bin
  entrypoint: /usr/local/bin/tko
  auto-version-annotation: git
  default-annotations:
    org.opencontainers.image.title: tko
    org.opencontainers.image.url: github.com/dskiff/tko
    org.opencontainers.image.source: github.com/dskiff/tko