build:
  base-ref: debian:bookworm-slim@sha256:0104b334637a5f19aa9c983a91b54c89887c0984081f2068983107a6f6c21eeb
  destination-path: /usr/local/bin
  entrypoint: /usr/local/bin/tko
  auto-version-annotation: git
  default-annotations:
    org.opencontainers.image.title: tko
    org.opencontainers.image.url: github.com/dskiff/tko
    org.opencontainers.image.source: github.com/dskiff/tko