build:
  base-ref: debian:bookworm-slim@sha256:96e378d7e6531ac9a15ad505478fcc2e69f371b10f5cdf87857c4b8188404716
  destination-path: /usr/local/bin
  entrypoint: /usr/local/bin/tko
  auto-version-annotation: git
  default-annotations:
    org.opencontainers.image.title: tko
    org.opencontainers.image.url: github.com/dskiff/tko
    org.opencontainers.image.source: github.com/dskiff/tko