build:
  base-ref: debian:bookworm-slim@sha256:e899040a73d36e2b36fa33216943539d9957cba8172b858097c2cabcdb20a3e2
  destination-path: /usr/local/bin
  entrypoint: /usr/local/bin/tko
  auto-version-annotation: git
  default-annotations:
    org.opencontainers.image.title: tko
    org.opencontainers.image.url: github.com/dskiff/tko
    org.opencontainers.image.source: github.com/dskiff/tko