build:
  base-ref: debian:bookworm-slim@sha256:88200866dfff7ea7f5cbcb6ec7c8a701889efe6fe859fe64d6990e4b07ea4171
  destination-path: /usr/local/bin
  entrypoint: /usr/local/bin/tko
  auto-version-annotation: git
  default-annotations:
    org.opencontainers.image.title: tko
    org.opencontainers.image.url: github.com/dskiff/tko
    org.opencontainers.image.source: github.com/dskiff/tko